In [1]:
import numpy as np

Ex 2. Randomly create a matrix of size (10, 5) then randomly assign values of 0 and 1 to the last column of this matrix.

In [5]:
np_matrix = np.random.rand(10,5)
np_matrix[:,4] = np.round(np_matrix[:,4])
np_matrix

array([[0.29661428, 0.40791823, 0.43967031, 0.04507083, 1.        ],
       [0.49696076, 0.12977883, 0.66618894, 0.2409987 , 0.        ],
       [0.92451257, 0.64870068, 0.28448864, 0.18374292, 1.        ],
       [0.30224778, 0.64436205, 0.2767244 , 0.28348799, 1.        ],
       [0.22577977, 0.46759329, 0.05786973, 0.58494642, 1.        ],
       [0.29948892, 0.07598478, 0.11121201, 0.24433729, 1.        ],
       [0.16854115, 0.82951562, 0.96662299, 0.41349696, 1.        ],
       [0.28565638, 0.25131757, 0.63080737, 0.87113577, 0.        ],
       [0.02368212, 0.40167024, 0.87983898, 0.55876391, 1.        ],
       [0.83958899, 0.67109312, 0.8568472 , 0.74467566, 1.        ]])

EX.3 Why we cannot use this index ? Please fix it !!
idx = [1,2,3,4,5]
np_matrix[idx,:]

In [7]:
idx = [1,2,3,4,5]
np_matrix[idx,:]

array([[0.49696076, 0.12977883, 0.66618894, 0.2409987 , 0.        ],
       [0.92451257, 0.64870068, 0.28448864, 0.18374292, 1.        ],
       [0.30224778, 0.64436205, 0.2767244 , 0.28348799, 1.        ],
       [0.22577977, 0.46759329, 0.05786973, 0.58494642, 1.        ],
       [0.29948892, 0.07598478, 0.11121201, 0.24433729, 1.        ]])

In [8]:
idx = [1,2,3,4,5]
np_matrix[idx.remove(5)]
np_matrix[idx,:]

array([[0.49696076, 0.12977883, 0.66618894, 0.2409987 , 0.        ],
       [0.92451257, 0.64870068, 0.28448864, 0.18374292, 1.        ],
       [0.30224778, 0.64436205, 0.2767244 , 0.28348799, 1.        ],
       [0.22577977, 0.46759329, 0.05786973, 0.58494642, 1.        ]])

Ex 4. Randomly create a data matrix of 10 samples with 5 features.

Then, randomly create a label vector for 10 samples.
Finally, seperate samples into 2 groups
Group 1 called train_data (label == 0)
Group 2 called test_data (label == 1)

In [21]:
matrix = np.random.randint(10,size = (10,5))
matrix

array([[9, 0, 8, 3, 0],
       [8, 6, 5, 0, 9],
       [2, 0, 4, 7, 6],
       [6, 7, 4, 2, 9],
       [5, 2, 0, 7, 6],
       [6, 6, 6, 9, 9],
       [5, 4, 8, 5, 3],
       [5, 1, 0, 2, 0],
       [0, 7, 5, 5, 3],
       [5, 4, 3, 3, 3]])

In [23]:
data_matrix = np.random.randint(2,size = 10)
dmatrix

array([0, 1, 1, 0, 1, 1, 0, 0, 1, 1])

In [24]:
train_data = matrix[np.where(data_matrix == 0)]
train_data

array([[9, 0, 8, 3, 0],
       [5, 4, 8, 5, 3],
       [0, 7, 5, 5, 3],
       [5, 4, 3, 3, 3]])

In [25]:
test_data = matrix[np.where(data_matrix == 1)]
test_data

array([[8, 6, 5, 0, 9],
       [2, 0, 4, 7, 6],
       [6, 7, 4, 2, 9],
       [5, 2, 0, 7, 6],
       [6, 6, 6, 9, 9],
       [5, 1, 0, 2, 0]])